### ISSUE TITLE
Issue with using Racon

### ISSUE THREAD

**Issue by charlottewright** [nanoporetech/pipeline-pinfish-analysis#11]
I am trying to use Racon within the pipeline-pinfish-analysis Snakefile but the workflow fails at the point of polishing the transcripts. The sdtout file suggests that the issue is with Racon.

The full error message is:

polish_clusters: 00:02:15 Polishing cluster 31b643a8-a0ec-4b7f-b8fe-a57b4ab35c48 of size 11
polish_clusters: 00:02:15 Failed running command: racon -t 10 -q -1 /tmp/pinfish_31b643a8-a0ec-4b7f-b8fe-a57b4ab35c4$
[Fri Nov 29 00:02:17 2019]
Error in rule polish_clusters:
jobid: 7
output: results/polished_transcripts.fas
shell:

/rds-d4/project/cj107/rds-cj107-jiggins-rds/projects/eratoCortexMapping/Nanopore/20191024_HW_Larva/pipeline-pinfi$

    (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Removing output files of failed job polish_clusters since they might be corrupted:
results/polished_transcripts.fas

Other people in my group who have previously used racon within this pipeline are also having the same problem with racon, suggesting that this is a bug with racon rather than my installation (I installed Racon from source - github - on November 21st).

Has anything changed with racon to account for why we are now having issues?
Note that I am using Racon v1.4.3 and I installed from source.

Thank you in advance for your help.

**Comment by charlottewright** [comment]
UPDATE: I since realised that there is a newer version of Racon (new Github page to old racon) - I have reinstalled Racon with the new version and will now try again.

**Comment by charlottewright** [comment]
We are still having issues with the pipeline at the point of racon.  I have installed the latest version of raocn (1.4.10) from source.

This is the error message in the stdout file:

```
polish_clusters: 22:03:03 Polishing cluster 7c3dbe49-2ce3-4046-bb21-13e62686fcaf of size 16
polish_clusters: 22:03:03 Failed running command: racon -t 15 -q -1 /tmp/pinfish_7c3dbe49-2ce3-4046-bb21-13e62686fcaf_986596328/reads.fq /tmp/pinfish_7c3dbe49-2ce3-4046-bb21-13e62686fcaf_986596328/alignments.sam /tmp/pinfish_7c3dbe49-2c$
[Fri Jan 31 22:03:05 2020]
Error in rule polish_clusters:
  jobid: 7
  output: results/polished_transcripts.fas

```

**Comment by bsipos** [comment]
Please update to the latest pinfish. There was an issue related to the latest samtools and I have rolled out a fix for it.
