### ISSUE TITLE
failed running the pipeline

### ISSUE THREAD

**Issue by Dan-Lt** [nanoporetech/pipeline-pinfish-analysis#13]
while running the snakemake command with my own data  I got an error in rule polish_clusters: see attached file 

what can be the problem ?

[2020-05-27T150620.743788.snakemake.log](https://github.com/nanoporetech/pipeline-pinfish-analysis/files/4689617/2020-05-27T150620.743788.snakemake.log)

**Comment by charlottewright** [comment]
Hi Dan,

I am having the same problem, did you find a fix to it?

**Comment by charlottewright** [comment]
UPDATE: updating to the latest version of racon (v1.4.13) by deleting then reinstalling from source fixed the error for me.

**Comment by Dan-Lt** [comment]
I'v updated racon to v1.4.13 and I still get the same error.

**Comment by bsipos** [comment]
This pipeline is no longer recommended for reference-based isoform analysis. Please use the newer [pipeline-nanopore-ref-isoforms](https://github.com/nanoporetech/pipeline-nanopore-ref-isoforms) pipeline instead.
