### ISSUE TITLE
Warning messages while running the pipeline

### ISSUE THREAD

**Issue by Dan-Lt** [nanoporetech/pipeline-pinfish-analysis#14]
I got the warning "[WARNING] Indexing parameters (-k, -w or -H) overridden by parameters used in the prebuilt index." in red, while running the snakemake command, my data is a directRNA fastq file and the config file has the same parameters as the defaut.

**Comment by bsipos** [comment]
Hello! The message is harmless, please just ignore it.

Also, this pipeline is no longer recommended for reference-based isoform analysis. Please use the newer [pipeline-nanopore-ref-isoforms](https://github.com/nanoporetech/pipeline-nanopore-ref-isoforms) pipeline instead.
