### ISSUE TITLE
Pipeline stuck on cluster_gff for big input files

### ISSUE THREAD

**Issue by MilesLuca** [nanoporetech/pipeline-pinfish-analysis#15]
Hi Botond,

This issue is related to [this ](https://github.com/nanoporetech/pinfish/issues/27)post on the pinfish github.

Pinfish appears to get stuck on the cluster_gff step.
The cluster_memberships.tsv  file reaches a maximum file size of 653089935 bytes and then stops.

The pipeline runs fine when supplying it with smaller fastq input files suggesting this may be a memory issue.
However, I do not see an option to supply more memory.

The input GFF is 4.4G and I'm running with -c 5 and -t 15. 

Changing thread number makes no difference, pipeline stuck at same step and same file size.

Thanks for your help,

Luca.

**Comment by bsipos** [comment]
This pipeline is no longer recommended for reference-based isoform analysis. Please use the newer [pipeline-nanopore-ref-isoforms](https://github.com/nanoporetech/pipeline-nanopore-ref-isoforms) pipeline instead.
