### ISSUE TITLE
Error running pipeline SIGSEGV panic

### ISSUE THREAD

**Issue by kyle-kroll** [nanoporetech/pipeline-pinfish-analysis#16]
Hello, I am trying to run the pipeline per the instructions on the homepage. 

My workflow is I created a conda environment and activated it. Then I ran
```
snakemake -j 16 all
```
The pipeline runs for a bit but I receive the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4ebd5f]

goroutine 5 [running]:
main.ReadTranscripts.func1(0xc4200100f0, 0x1, 0x1, 0xc4200820c0)
	/home/OXFORDNANOLABS/bsipos/gt/pinfish/collapse_partials/input.go:49 +0x57f
created by main.ReadTranscripts
	/home/OXFORDNANOLABS/bsipos/gt/pinfish/collapse_partials/input.go:28 +0x7f
```

I am running this from within a conda environment with python 3.7, samtools 1.9, and snakemake 5.27.4. I am using racon 1.4.0 compiled from source. This is running on a server cluster through my university with 16 cores and 32GB RAM. Modules loaded into the cluster are gcc 6.2.0 and go 1.9.2. The full log dump is here [2020-11-06T111431.450252.snakemake.log](https://github.com/nanoporetech/pipeline-pinfish-analysis/files/5502241/2020-11-06T111431.450252.snakemake.log)

Thanks for any help.

**Comment by bsipos** [comment]
Could you please re-run snakemake with the `--keep-incomplete` option and check if the intermediary files look all right? For example if the BAM file is not empty.

**Comment by bsipos** [comment]
This pipeline is no longer recommended for reference-based isoform analysis. Please use the newer [pipeline-nanopore-ref-isoforms](https://github.com/nanoporetech/pipeline-nanopore-ref-isoforms) pipeline instead.
