### ISSUE TITLE
Racon error

### ISSUE THREAD

**Issue by qh1134269149** [nanoporetech/pipeline-pinfish-analysis#5]
Hi，I used the pipeline-pinfish-analysis to analysis my Arabidopsis thaliana from direct RNA seq reads using standard parameters, but I get an the following error:  
>>>
polish_clusters: 10:32:51 Polishing cluster 8b9fd65e-5402-4ad2-a728-d14cd88556a3 of size 112
polish_clusters: 10:32:51 Failed running command: racon -t 50 -q -1  /tmp/pinfish_8b9fd65e-5402-4ad2-a728-d14cd88556a3_167235147/reads.fq /tmp/pinfish_8b9fd65e-5402-4ad2-a728-d14cd88556a3_167235147/alignments.sam /tmp/pinfish_8b9fd65e-5402-4ad2-a728-d14cd88556a3_167235147/reference.fq > /tmp/pinfish_8b9fd65e-5402-4ad2-a728-d14cd88556a3_167235147/consensus.fq - exit status 132
polish_clusters: 10:33:24 Polishing cluster 87932704-7fab-414f-bf4a-ac142d799658 of size 293
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4ed5c9]

goroutine 1 [running]:
main.getMedian(0xc000122a80, 0x125, 0x125, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/stephen/miniconda3/conda-bld/pinfish_1548434961576/work/polish_clusters/polish.go:119 +0x99
main.CreateReference(0xc00842dfb5, 0x24, 0xc000122a80, 0x125, 0x125, 0xc1d8ad1e00, 0x3b, 0x0, 0x2d, 0x338)
        /home/stephen/miniconda3/conda-bld/pinfish_1548434961576/work/polish_clusters/polish.go:72 +0x74
main.PolishCluster(0xc00842dfb5, 0x24, 0xc000122a80, 0x125, 0x125, 0xc0000f2240, 0x0, 0x0, 0x32, 0x0, ...)
        /home/stephen/miniconda3/conda-bld/pinfish_1548434961576/work/polish_clusters/polish.go:25 +0x2b7
main.main()
        /home/stephen/miniconda3/conda-bld/pinfish_1548434961576/work/polish_clusters/main.go:46 +0x32c
polish_clusters: 10:33:49 Polishing cluster d887e9f4-4615-47f9-82cf-9a0110a35226 of size 13
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4ed5c9]

goroutine 1 [running]:
main.getMedian(0xc1c1b30000, 0xd, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/stephen/miniconda3/conda-bld/pinfish_1548434961576/work/polish_clusters/polish.go:119 +0x99
main.CreateReference(0xc003b1eac5, 0x24, 0xc1c1b30000, 0xd, 0xd, 0xc1c1ab8980, 0x3b, 0x0, 0x2d, 0x460)
        /home/stephen/miniconda3/conda-bld/pinfish_1548434961576/work/polish_clusters/polish.go:72 +0x74
main.PolishCluster(0xc003b1eac5, 0x24, 0xc1c1b30000, 0xd, 0xd, 0xc0000f2240, 0x0, 0x0, 0x32, 0x0, ...)
        /home/stephen/miniconda3/conda-bld/pinfish_1548434961576/work/polish_clusters/polish.go:25 +0x2b7
main.main()
        /home/stephen/miniconda3/conda-bld/pinfish_1548434961576/work/polish_clusters/main.go:46 +0x32c
<<<
Can you give me some advice? Looking forward to your response.

**Comment by bsipos** [comment]
Did you install racon from conda by any chance? In that case it might be broken on your architecture. You can fix that by installing it from source.

**Comment by qh1134269149** [comment]
Thank you for your reply. I installed recon from Conda. Do I need to reinstall from the source ?

**Comment by bsipos** [comment]
Yes, based on your error you will have to install racon from source.
