### ISSUE TITLE
ggplot2 code for your plots

### ISSUE THREAD

**Issue by splaisan** [nanoporetech/pipeline-pinfish-analysis#7]
Dear Botond,
Lets try laziness !
Would you by chance have a parser for the polished_transcripts_collapsed.gff file that would produce your nice plots.
The summary text file is nicely readable for human but not as easily for R at first glance.
Thanks
Stephane

**Comment by bsipos** [comment]
You mean the visualization of the gffcompare output? That is available at https://github.com/nanoporetech/wub/blob/master/scripts/plot_gffcmp_stats.py

**Comment by splaisan** [comment]
Thanks a million, saves me hour(s)
 :-)
