### ISSUE TITLE
Adding gene annotations in spliced_bam2gff

### ISSUE THREAD

**Issue by mvemulap** [nanoporetech/pipeline-pinfish-analysis#8]
Hello,

   Can you let me know how to add the gene annotations to the gff file produced by spliced_bam2gff.
   My output file (raw_transcripts.gff) contains read names in the gene id and transcript id columns.

   I am declaring the file to be used in config.yaml:
   genome_annot: "/pathto/ReferenceData/Homo_sapiens.GRCh38.97.gff3.gz"

Please let me know if I need to change anything or if I am missing something.

Thanks,
Meg

**Comment by bsipos** [comment]
The pinfish pipeline does not use prior annotation at all, hence the IDs have no relation to existing annotation. If you want to "match up" transcripts from the pipeline with the existing annotation you will have to use the [gffcompare](https://anaconda.org/bioconda/gffcompare) tool.

**Comment by mvemulap** [comment]
Got it ! Thanks so much!
